# Generated by Django 3.2.9 on 2022-02-28 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='applied',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, null=True)),
                ('Email', models.EmailField(max_length=200, null=True)),
                ('Mobile', models.CharField(max_length=200, null=True)),
                ('Address', models.CharField(max_length=200, null=True)),
                ('City', models.CharField(max_length=200, null=True)),
                ('reference', models.CharField(choices=[('Fb', 'Fackbook'), ('Insta', 'Instagram'), ('Youtube', 'Youtube'), ('Website', 'Website'), ('Others', 'Others')], max_length=20, null=True)),
                ('trm', models.BooleanField(default=False)),
            ],
        ),
    ]
